kind: playground
title: SilverStack CI/CD Stack
description: Custom-domain CI/CD stack with Jenkins, SonarQube, and Nexus - each service exposed via Cloudflare Tunnel with SSL on your own domain
categories:
    - linux
    - ci-cd
    - containers
playground:
    networks:
        - name: local
          subnet: 172.16.0.0/24
    machines:
        - name: dev-machine
          users:
            - name: root
            - name: ibtisam
              default: true
          drives:
            - source: oci://ghcr.io/ibtisam-iq/dev-cicd-rootfs:latest
              mount: /
              size: 30GiB
          network:
            interfaces:
                - network: local
          resources:
            cpuCount: 1
            ramSize: 1GiB

        - name: jenkins-server
          users:
            - name: root
            - name: ibtisam
              default: true
          drives:
            - source: oci://ghcr.io/ibtisam-iq/jenkins-rootfs:latest
              mount: /
              size: 40GiB
          network:
            interfaces:
                - network: local
          resources:
            cpuCount: 3
            ramSize: 4GiB

        - name: sonarqube-server
          users:
            - name: root
            - name: ibtisam
              default: true
          drives:
            - source: oci://ghcr.io/ibtisam-iq/sonarqube-rootfs:latest
              mount: /
              size: 40GiB
          network:
            interfaces:
                - network: local
          resources:
            cpuCount: 3
            ramSize: 6GiB

        - name: nexus-server
          users:
            - name: root
            - name: ibtisam
              default: true
          drives:
            - source: oci://ghcr.io/ibtisam-iq/nexus-rootfs:latest
              mount: /
              size: 40GiB
          network:
            interfaces:
                - network: local
          resources:
            cpuCount: 3
            ramSize: 5GiB

    tabs:
        - kind: ide
          name: IDE
          machine: dev-machine
        - kind: terminal
          name: dev
          machine: dev-machine
        - kind: terminal
          name: jenkins
          machine: jenkins-server
        - kind: terminal
          name: sonarqube
          machine: sonarqube-server
        - kind: terminal
          name: nexus
          machine: nexus-server
        - kind: http-port
          name: "Jenkins UI"
          machine: jenkins-server
          number: 80
        - kind: http-port
          name: "SonarQube UI"
          machine: sonarqube-server
          number: 80
        - kind: http-port
          name: "Nexus UI"
          machine: nexus-server
          number: 80

    accessControl:
        canList:
            - anyone
        canRead:
            - anyone
        canStart:
            - anyone
