# Database
sonar.jdbc.username=sonar
sonar.jdbc.password=sonar_password
sonar.jdbc.url=jdbc:postgresql://localhost:5432/sonarqube

# Web Server
sonar.web.host=0.0.0.0
sonar.web.port=__SONARQUBE_PORT__
sonar.web.context=/
sonar.web.workers=4

# Elasticsearch
sonar.search.host=127.0.0.1
sonar.search.port=9001

# Compute Engine
sonar.ce.javaOpts=-Xmx2G -Xms512m -XX:+UseG1GC

# Web Server Java Options
sonar.web.javaOpts=-Xmx1G -Xms256m -XX:+UseG1GC

# Elasticsearch Java Options
sonar.search.javaOpts=-Xms1G -Xmx1G
